site_title: "Growth Partner Pros - Turn AI Disruption into Your Greatest Advantage"
site_description: "Growth Partner Pros helps forward-thinking leaders and businesses harness the power of AI to achieve 10x productivity, streamline operations, and create competitive advantage."

logo: ""

social:
  linkedin: "https://linkedin.com/company/growthpartnerpros"
  twitter: "https://twitter.com/growthpartnerpros"
  instagram: "https://instagram.com/growthpartnerpros"

seo:
  keywords: "AI consulting, AI transformation, business productivity, AI strategy, leadership training, automation, digital transformation"
  google_analytics: ""

