[build]
  publish = "."
  command = "echo 'No build step required for static site'"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"

# Enable Netlify Identity for CMS authentication
[context.production]
  environment = { NODE_ENV = "production" }

# Form handling
[forms]
  settings = { spam_protection = true }

# Enable Git Gateway for Netlify CMS
[template.environment]
  NETLIFY_CMS_MANUAL_INIT = "true"

